<a href="https://colab.research.google.com/github/SakshiMuksiya/Data-science-with-python-Wipro-course/blob/main/Numpy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#NUMPY AND PANDAS

In [3]:
#Introduction to Numpy
import numpy as np

In [4]:
#Create a two dimensional 3*3 array and perform ndim, shape, slicing operations on it.

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:\n", arr1)
ndim = arr1.ndim
shape = arr1.shape
slicing = arr1[0:2, 0:2]  # Slicing the first two rows and first two columns
print("Number of dimensions:", ndim)
print("Shape of the array:", shape)
print("Sliced array:\n", slicing)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of dimensions: 2
Shape of the array: (3, 3)
Sliced array:
 [[1 2]
 [4 5]]


In [5]:
#Create one dimensional array and perform ndim, shape, reshape operations on it.
arr2 = np.array([1, 2, 3, 4, 5, 6])
ndim = arr2.ndim
shape = arr2.shape
reshaped_arr = arr2.reshape(2, 3)  # Reshaping to 2 rows and 3 columns
print("Array:\n", arr2)
print("Number of dimensions:", ndim)
print("Shape of the array:", shape)
print("Reshaped array:\n", reshaped_arr)

Array:
 [1 2 3 4 5 6]
Number of dimensions: 1
Shape of the array: (6,)
Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [7]:
#Introduction to Pandas
import pandas as pd

In [12]:
#download the dataset and rename to cars.csv
#Dataset: https://www.kaggle.com/uciml/autompg-dataset?select=auto-mpg.csv or https://archive.ics.uci.edu/ml/datasets/Auto+MPG

#a. Import Pandas

#b. Import the Cars dataset and store the Pandas DataFrame in a variable called cars.
dataset_path = 'cars.csv'

#c. inspect the first 10 rows of the DataFrame.
cars = pd.read_csv(dataset_path)
print(cars.head(10))
print()

#d. inspect the dataframe cars by printing cars
print(cars)
print()

#e. inspect the last 5 rows
print(cars.tail(5))
print()

#f. get some meta information on dataframe like number of rows, columns, column names, data types etc.
print("Number of rows:", cars.shape[0], '\n')
print("Number of columns:", cars.shape[1], '\n')
print("Column names:", cars.columns.tolist(), '\n')
print("Data types:")
print(cars.dtypes)

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skyla

In [13]:
#dataset: https://www.kaggle.com/datasets/farhanmd29/50-startups

#a. Create dataframe using pandas
#b. Read the data from 50_startups.csv file and load the data into the dataframe
startup = pd.read_csv('50_Startups.csv')
print(startup)
print()

#c. Check the statistical summary
print(startup.describe())
print()

#d. Check for corelation coefficient between the dependent and independent variables
print("\nCorrelation Matrix:")
print(startup.corr(numeric_only=True))

print("\nCorrelation with Profit:")
print(startup[['R&D Spend', 'Administration', 'Marketing Spend']].corrwith(startup['Profit']))

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       